### ISSUE TITLE
Config option to perform mib mapping on values

### ISSUE THREAD

**Issue by axrayn** [logstash-plugins/logstash-integration-snmp#39]
Could we get a boolean config option to specify whether to perform mib translation on OID values returned by the input.

e.g. sysObjID would be returned as:
`iso.org.dod.internet.private.enterprises.netSnmp.netSnmpEnumerations.netSnmpAgentOIDs.linux`
instead of:
`.1.3.6.1.4.1.8072.3.2.10`

Not sure how we'd handle the oid_root_skip portion of this as presumably we wouldn't want to be assume the same length as the varbind oid

**Comment by edmocosta** [comment]
Hey there!

We've moved this issue into this new SNMP integration plugin, which combines the [logstash-input-snmp](https://github.com/logstash-plugins/logstash-input-snmp) and [logstash-input-snmptrap](https://github.com/logstash-plugins/logstash-input-snmptrap) plugins into one, and finally adds support to this feature by setting `oid_map_field_values => true`. For now, it uses the same OID field's format, including `oid_root_skip` and `oid_path_length` configs.

Before upgrading, please have a look at the [migration notes](https://github.com/logstash-plugins/logstash-integration-snmp/blob/main/docs/index.asciidoc#migrating-to-logstash-integration-snmp-from-individual-plugins), as the new plugin introduced a few breaking changes compared to individual one. It will be bundled by default with Logstash in a future release (e.g. 8.15 or 8.16).

Thanks!
