### ISSUE TITLE
IPv6 host

### ISSUE THREAD

**Issue by SkiAn2007** [logstash-plugins/logstash-integration-snmp#48]
How to setup IPv6 listen?

> [2019-01-18T10:26:27,804][INFO ][logstash.inputs.snmptrap ] It's a Trap! {:Port=>10620, :Community=>["public"], :Host=>"fd00:192:168:67::41"}
> [2019-01-18T10:26:27,807][WARN ][logstash.inputs.snmptrap ] SNMP Trap listener died {:exception=>java.nio.channels.UnsupportedAddressTypeException

**Comment by edmocosta** [comment]
The IPv6 support was added to this integration `snmptrap` plugin. It replaces the individual [logstash-input-snmptrap](https://github.com/logstash-plugins/logstash-input-snmptrap) plugin and will be bundled by default with Logstash in the future. Before upgrading, please check the migration [notes](https://github.com/logstash-plugins/logstash-integration-snmp/blob/main/docs/index.asciidoc#migrating-to-logstash-integration-snmp-from-individual-plugins) out.
Feel free to re-open this issue if the problem still persists. Thanks!
