### ISSUE TITLE
Support equivalent of `disableAuthorization yes`

### ISSUE THREAD

**Issue by cleeland** [logstash-plugins/logstash-integration-snmp#51]
`snmptrapd` from net-snmp offers a configuration option wherein traps are not checked for any authorization information, thereby enabling reception and processing of all traps. It appears that this option is not supported by logstash-input-snmptrap.

The default behavior for ruby-snmp (on which this plugin is built) is to accept all notifications, but the input plugin does not appear to offer a way to provide *no* community string, since it defaults to `public`.

**Comment by edmocosta** [comment]
Hey there!

We've moved this issue into this new SNMP integration plugin repository, which combines the [logstash-input-snmp](https://github.com/logstash-plugins/logstash-input-snmp) and [logstash-input-snmptrap](https://github.com/logstash-plugins/logstash-input-snmptrap) plugins into one, and finally adds support to this feature by setting `community => []`. We've also updated the docs to describe this behaviour. 

Before upgrading, please have a look at the [migration notes](https://github.com/logstash-plugins/logstash-integration-snmp/blob/main/docs/index.asciidoc#migrating-to-logstash-integration-snmp-from-individual-plugins), as the new plugin introduced a few breaking changes compared to individual one. It will be bundled by default with Logstash in a future release (e.g. 8.15 or 8.16).

Thanks!
